//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sission3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Session2Entities : DbContext
    {
        private static Session2Entities _context;
        public Session2Entities()
            : base("name=Session2Entities")
        {
        }

        public static Session2Entities GetContext()
        {
            if (_context == null)
                _context = new Session2Entities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Абонент> Абонент { get; set; }
        public virtual DbSet<Города> Города { get; set; }
        public virtual DbSet<Договор> Договор { get; set; }
        public virtual DbSet<Разговоры> Разговоры { get; set; }
        public virtual DbSet<Тариф> Тариф { get; set; }
        public virtual DbSet<Телефон> Телефон { get; set; }
    }
}
