//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sission3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Разговоры
    {
        public int ID { get; set; }
        public System.DateTime Дата_разговора { get; set; }
        public int Продолжительность { get; set; }
        public int ID_Телефона { get; set; }
        public int Код_Города { get; set; }
    
        public virtual Города Города { get; set; }
        public virtual Телефон Телефон { get; set; }
    }
}
